### ISSUE TITLE
Line 1082: bad argument #1 to 'resolve'

### ISSUE THREAD

**Issue by SleepyZephrix** [MCJack123/tracc#1]
![image](https://github.com/MCJack123/tracc/assets/137726898/fb4d8908-0eb1-4201-983a-0f076c288236)

I'm on the most recent CC:T version for 1.18.2 which is 1.101.3. How would I resolve this error?

**Comment by MCJack123** [comment]
You need to give it a file to play.

**Comment by SleepyZephrix** [comment]
Ah gotcha. Sorry for wasting your time
